//> Scanning token-type
package edu.sou.cs452.drop;

enum TokenType {
  INIT, ITER, TRANSLATION, OR, ROTATION, LEFT_BRACE, RIGHT_BRACE, LEFT_PAREN, RIGHT_PAREN,
  COMMA, NUMBER, CROSS, SEMICOLON, DOT, LEFT_BRACKET, RIGHT_BRACKET, EOF
}
